version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongodata:/data/db
    networks:
      - myNetwork

  nestjs_backend:
    container_name: nestjs_backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - myNetwork

  python_backend:
    container_name: python_backend
    build: ./backend-python
    ports:
      - "5000:5000"
    depends_on:
      - nestjs_backend
    networks:
      - myNetwork

  angular_frontend:
    container_name: angular_frontend
    build: ./frontend-Angular
    ports:
      - "8080:80"
    depends_on:
      - nestjs_backend
    networks:
      - myNetwork

networks:
  myNetwork:
    name: myNetwork
    driver: bridge

volumes:
  mongodata:
    driver: local
